FROM python:3.12

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip
RUN pip install mlflow

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "./mlflow-artifacts", "--host", "0.0.0.0", "--port", "5000"]
